clc;
z = complex(0.036,0.3); y = complex(0,4.22/1000000);
Length  =130;
Z = z * Length; Y = y*Length;
Vs3ph = 345; Ism = 0.4;
As = -acos(0.95);
Vs = Vs3ph/sqrt(3);
Is = Ism * complex(cos(As),sin(As));
A = (Z*Y)/2+1;
B = Z;
C = Y*((Z*Y)/4+1);
D = A;
ABCD = [A B;C D];
VrIr = inv(ABCD) * [Vs; Is];
Vr = VrIr(1);
Vr3ph = sqrt(3) * abs(Vr);
Ir = VrIr(2);
Irm = 1000*abs(Ir);
pfr = cos(angle(Vr)-angle(Ir));
Sr = 3*Vr*conj(Ir);
REG = (Vs3ph/abs(ABCD(1,1))- Vr3ph)/Vr3ph * 100;
fprintf('Vs = %g L-L kV\n',Vs3ph);
fprintf('Is = %g A\n',Ism);
fprintf('Ir = %g A \n',Irm)
fprintf('pf = %g\n',pfr);
fprintf('Vr = %g L-L kV\n',Vr3ph);
fprintf('Pr = %g MW\n',real(Sr));
fprintf('Qr = %g Mvar\n',imag(Sr));
fprintf('Percentage Voltage Reg. = %g\n',REG);